const player = (id, name) => ({
  id,
  name,
  documentId: `ID-${id.toUpperCase()}`,
  apto: true,
  dni: String(30000000 + Number(id.replace(/\D/g, "").slice(-2) || "1")),
  signed: false,
  change: "sin_cambio",
  notes: "",
  goals: 0,
  yellowCards: 0,
  redCard: false,
  redReason: "",
});

const teamSheet = (prefix, names) =>
  names.map((name, index) => player(`${prefix}_${index + 1}`, name));

const buildSheet = ({
  matchId,
  homePrefix,
  awayPrefix,
  homeNames,
  awayNames,
  observations = "",
  incidents = [],
  updatedAtIso,
}) => ({
  matchId,
  homePlayers: teamSheet(homePrefix, homeNames),
  awayPlayers: teamSheet(awayPrefix, awayNames),
  observations,
  incidents,
  updatedAtIso,
});

export const seedPlanilleros = [
  {
    id: "u_plan_1",
    name: "Planillero Demo",
    username: "planillero",
    email: "planillero@tdefa.local",
    phone: "+54 11 5555-0001",
    dni: "30000001",
    status: "activo",
    assignedMatchesCount: 6,
    completedMatchesCount: 3,
    createdAtIso: "2025-01-10",
  },
  {
    id: "u_plan_2",
    name: "Carlos Ruiz",
    username: "carlos",
    email: "carlos@tdefa.local",
    phone: "+54 11 5555-0002",
    dni: "30000002",
    status: "activo",
    assignedMatchesCount: 2,
    completedMatchesCount: 2,
    createdAtIso: "2025-03-22",
  },
  {
    id: "u_plan_3",
    name: "Maria Lopez",
    username: "maria",
    email: "maria@tdefa.local",
    phone: "+54 11 5555-0003",
    dni: "30000003",
    status: "activo",
    assignedMatchesCount: 2,
    completedMatchesCount: 2,
    createdAtIso: "2025-06-05",
  },
  {
    id: "u_plan_4",
    name: "Agustin Pereira",
    username: "agustin",
    email: "agustin@tdefa.local",
    phone: "+54 11 5555-0004",
    dni: "30000004",
    status: "inactivo",
    assignedMatchesCount: 0,
    completedMatchesCount: 4,
    createdAtIso: "2024-10-01",
  },
];

export const seedMatches = [
  {
    id: "m_1001",
    tournament: "Torneo Senior A",
    status: "pendiente",
    dateIso: "2026-06-13",
    time: "10:00",
    venue: "Sede Pilar",
    pitch: "Cancha 1",
    homeTeam: { id: "t_1", name: "Los Pinos", shortName: "LOS" },
    awayTeam: { id: "t_2", name: "Deportivo Norte", shortName: "DNO" },
    score: { home: 0, away: 0 },
    assignedPlanilleroId: "u_plan_1",
    reopenReason: null,
  },
  {
    id: "m_1002",
    tournament: "Copa de Campeones",
    status: "en_carga",
    dateIso: "2026-06-13",
    time: "11:30",
    venue: "Sede Pilar",
    pitch: "Cancha 2",
    homeTeam: { id: "t_3", name: "Chacarita", shortName: "CHA" },
    awayTeam: { id: "t_4", name: "Rivadavia", shortName: "RIV" },
    score: { home: 1, away: 0 },
    assignedPlanilleroId: "u_plan_1",
    reopenReason: null,
  },
  {
    id: "m_1003",
    tournament: "Torneo Senior B",
    status: "terminado",
    dateIso: "2026-06-06",
    time: "16:00",
    venue: "Sede Pilar",
    pitch: "Cancha 3",
    homeTeam: { id: "t_5", name: "San Martin", shortName: "SAM" },
    awayTeam: { id: "t_6", name: "Atlas FC", shortName: "ATL" },
    score: { home: 2, away: 1 },
    assignedPlanilleroId: "u_plan_1",
    reopenReason: null,
  },
  {
    id: "m_1004",
    tournament: "Primera Flex",
    status: "pendiente",
    dateIso: "2026-06-14",
    time: "09:30",
    venue: "Sede Pilar",
    pitch: "Cancha 4",
    homeTeam: { id: "t_9", name: "Nordelta FC", shortName: "NFC" },
    awayTeam: { id: "t_10", name: "Pilar Blue", shortName: "PBL" },
    score: { home: 0, away: 0 },
    assignedPlanilleroId: "u_plan_1",
    reopenReason: null,
  },
  {
    id: "m_2001",
    tournament: "Clausura Premier",
    status: "reabierto",
    dateIso: "2026-06-07",
    time: "13:00",
    venue: "Sede Pilar",
    pitch: "Cancha 5",
    homeTeam: { id: "t_7", name: "Belgrano", shortName: "BEL" },
    awayTeam: { id: "t_8", name: "Ferro", shortName: "FER" },
    score: { home: 1, away: 1 },
    assignedPlanilleroId: "u_plan_1",
    reopenReason: "Falta firma del capitan",
  },
  {
    id: "m_2002",
    tournament: "Clausura Premier",
    status: "terminado",
    dateIso: "2026-06-01",
    time: "15:00",
    venue: "Sede Pilar",
    pitch: "Cancha 6",
    homeTeam: { id: "t_11", name: "Tigre FC", shortName: "TIG" },
    awayTeam: { id: "t_12", name: "Pilar Senior", shortName: "PSR" },
    score: { home: 3, away: 2 },
    assignedPlanilleroId: "u_plan_1",
    reopenReason: null,
  },
  {
    id: "m_3001",
    tournament: "Reserva A",
    status: "en_carga",
    dateIso: "2026-06-13",
    time: "12:00",
    venue: "Sede Escobar",
    pitch: "Cancha 1",
    homeTeam: { id: "t_13", name: "Escobar FC", shortName: "ESC" },
    awayTeam: { id: "t_14", name: "Victoria", shortName: "VIC" },
    score: { home: 0, away: 0 },
    assignedPlanilleroId: "u_plan_2",
    reopenReason: null,
  },
  {
    id: "m_3002",
    tournament: "Reserva A",
    status: "pendiente",
    dateIso: "2026-06-15",
    time: "18:30",
    venue: "Sede Escobar",
    pitch: "Cancha 2",
    homeTeam: { id: "t_15", name: "Benavidez", shortName: "BEN" },
    awayTeam: { id: "t_16", name: "Maschwitz", shortName: "MAS" },
    score: { home: 0, away: 0 },
    assignedPlanilleroId: "u_plan_2",
    reopenReason: null,
  },
  {
    id: "m_4001",
    tournament: "Futbol 7",
    status: "terminado",
    dateIso: "2026-06-03",
    time: "20:00",
    venue: "Sede Norte",
    pitch: "Cancha 2",
    homeTeam: { id: "t_17", name: "Aston Birra", shortName: "ASB" },
    awayTeam: { id: "t_18", name: "La Banda", shortName: "LBD" },
    score: { home: 4, away: 4 },
    assignedPlanilleroId: "u_plan_3",
    reopenReason: null,
  },
  {
    id: "m_4002",
    tournament: "Futbol 7",
    status: "reabierto",
    dateIso: "2026-06-05",
    time: "21:15",
    venue: "Sede Norte",
    pitch: "Cancha 3",
    homeTeam: { id: "t_19", name: "Sanfer United", shortName: "SFU" },
    awayTeam: { id: "t_20", name: "Delta Club", shortName: "DEL" },
    score: { home: 2, away: 2 },
    assignedPlanilleroId: "u_plan_3",
    reopenReason: "Corregir tarjeta roja",
  },
];

export const seedSheets = {
  m_1001: buildSheet({
    matchId: "m_1001",
    homePrefix: "lp",
    awayPrefix: "dn",
    homeNames: ["A. Gomez", "B. Rojas", "C. Vega", "D. Luna", "E. Farias"],
    awayNames: ["L. Torres", "M. Castro", "N. Molina", "O. Perez", "P. Silva"],
    observations: "Pendiente de apertura en campo.",
    updatedAtIso: "2026-06-08T16:15:00.000Z",
  }),
  m_1002: buildSheet({
    matchId: "m_1002",
    homePrefix: "cha",
    awayPrefix: "riv",
    homeNames: ["A. Suarez", "B. Romero", "C. Diaz", "D. Sosa", "E. Rivas", "F. Gomez"],
    awayNames: ["L. Torres", "M. Castro", "N. Molina", "O. Perez", "P. Silva", "Q. Arias"],
    observations: "Planilla abierta para carga en campo.",
    incidents: [
      { id: "i_1", minute: 12, type: "amarilla", team: "home", label: "A. Suarez" },
      { id: "i_2", minute: 28, type: "gol", team: "home", label: "B. Romero" },
    ],
    updatedAtIso: "2026-06-08T16:20:00.000Z",
  }),
  m_1003: buildSheet({
    matchId: "m_1003",
    homePrefix: "sam",
    awayPrefix: "atl",
    homeNames: ["J. Mendez", "K. Duarte", "L. Medina", "M. Sosa", "N. Vera"],
    awayNames: ["R. Ledesma", "S. Ortiz", "T. Ruiz", "U. Prieto", "V. Benitez"],
    observations: "Planilla finalizada y lista para auditoria.",
    incidents: [
      { id: "i_3", minute: 18, type: "gol", team: "home", label: "J. Mendez" },
      { id: "i_4", minute: 51, type: "gol", team: "away", label: "R. Ledesma" },
      { id: "i_5", minute: 78, type: "gol", team: "home", label: "K. Duarte" },
    ],
    updatedAtIso: "2026-06-08T16:30:00.000Z",
  }),
  m_1004: buildSheet({
    matchId: "m_1004",
    homePrefix: "nfc",
    awayPrefix: "pbl",
    homeNames: ["D. Herrera", "E. Pena", "F. Mena", "G. Cruz", "H. Soria"],
    awayNames: ["A. Lucero", "B. Vera", "C. Ruiz", "D. Simo", "E. Jara"],
    observations: "Partido listo para ser abierto.",
    updatedAtIso: "2026-06-08T16:32:00.000Z",
  }),
  m_2001: buildSheet({
    matchId: "m_2001",
    homePrefix: "bel",
    awayPrefix: "fer",
    homeNames: ["P. Blanco", "Q. Rios", "R. Gomez", "S. Duarte", "T. Paredes"],
    awayNames: ["A. Rossi", "B. Soto", "C. Nievas", "D. Coronel", "E. Salas"],
    observations: "Reabrir para corregir firma pendiente del capitan.",
    incidents: [{ id: "i_6", minute: 63, type: "nota", team: "home", label: "Falta firma del capitan" }],
    updatedAtIso: "2026-06-08T16:40:00.000Z",
  }),
  m_2002: buildSheet({
    matchId: "m_2002",
    homePrefix: "tig",
    awayPrefix: "psr",
    homeNames: ["N. Lagos", "O. Riba", "P. Ojeda", "Q. Duarte", "R. Mora"],
    awayNames: ["S. Varela", "T. Sandez", "U. Lopez", "V. Arias", "W. Gomez"],
    observations: "Resultado confirmado por ambos capitanes.",
    incidents: [
      { id: "i_7", minute: 7, type: "gol", team: "home", label: "N. Lagos" },
      { id: "i_8", minute: 71, type: "gol", team: "away", label: "V. Arias" },
    ],
    updatedAtIso: "2026-06-08T16:42:00.000Z",
  }),
  m_3001: buildSheet({
    matchId: "m_3001",
    homePrefix: "esc",
    awayPrefix: "vic",
    homeNames: ["A. Campos", "B. Britez", "C. Cardozo", "D. Bruno", "E. Salvatierra"],
    awayNames: ["F. Chavez", "G. Escalante", "H. Marin", "I. Diaz", "J. Carrizo"],
    observations: "Control inicial de documentación en proceso.",
    updatedAtIso: "2026-06-08T16:44:00.000Z",
  }),
  m_3002: buildSheet({
    matchId: "m_3002",
    homePrefix: "ben",
    awayPrefix: "mas",
    homeNames: ["K. Porta", "L. Bernal", "M. Aguero", "N. Lemos", "O. Cejas"],
    awayNames: ["P. Balbuena", "Q. Sena", "R. Grana", "S. Diaz", "T. Mendez"],
    observations: "",
    updatedAtIso: "2026-06-08T16:46:00.000Z",
  }),
  m_4001: buildSheet({
    matchId: "m_4001",
    homePrefix: "asb",
    awayPrefix: "lbd",
    homeNames: ["A. Coria", "B. Yedro", "C. Ortiz", "D. Acuna", "E. Iriarte"],
    awayNames: ["F. Meza", "G. Benavente", "H. Juarez", "I. Viana", "J. Longo"],
    observations: "Cierre con empate y sin observaciones mayores.",
    incidents: [
      { id: "i_9", minute: 55, type: "amarilla", team: "away", label: "G. Benavente" },
    ],
    updatedAtIso: "2026-06-08T16:48:00.000Z",
  }),
  m_4002: buildSheet({
    matchId: "m_4002",
    homePrefix: "sfu",
    awayPrefix: "del",
    homeNames: ["K. Flores", "L. Roldan", "M. Ledesma", "N. Quintana", "O. Perez"],
    awayNames: ["P. Caruso", "Q. Perrone", "R. Tula", "S. Herrera", "T. Mateo"],
    observations: "Partido reabierto para ajustar una expulsion cargada al equipo equivocado.",
    incidents: [
      { id: "i_10", minute: 61, type: "expulsion", team: "away", label: "Q. Perrone" },
    ],
    updatedAtIso: "2026-06-08T16:50:00.000Z",
  }),
};
